"""Type stubs for the gitxtend compiled module. Contract: docs/API.md."""

from __future__ import annotations

import os

_Path = str | os.PathLike[str]

class RepoStatus:
    path: str
    state: str  # "up-to-date"|"ahead"|"behind"|"diverged"|"dirty"|"no-remote"|"error"
    local_branch: str | None
    tracking_branch: str | None
    local_sha: str | None
    remote_sha: str | None
    ahead_count: int
    behind_count: int
    new_remote_commits: list[str]
    is_dirty: bool
    error: str | None

def is_git_repo(path: _Path) -> bool: ...
def is_clean(path: _Path) -> bool: ...
def current_branch(path: _Path) -> str | None: ...
def tracking_branch(path: _Path) -> str | None: ...
def head_sha(path: _Path) -> str | None: ...
def remote_head_sha(path: _Path, remote_ref: str = ...) -> str | None: ...
def ahead_behind(path: _Path, upstream: str) -> tuple[int, int]: ...
def rev_list_count(path: _Path, range_spec: str) -> int: ...
def log_subjects(path: _Path, range_spec: str, max_count: int = ...) -> list[str]: ...
def remote_urls(path: _Path) -> dict[str, str]: ...
def last_commit_date(path: _Path) -> str | None: ...
def status_counts(path: _Path) -> tuple[int, int]: ...
def fetch(path: _Path, remote: str | None = ...) -> bool: ...
def repo_status(path: _Path, fetch: bool = ...) -> RepoStatus: ...
